"use strict";

export const articlesDB =
[
  {
    nombreBlog:"En Busca de Tormentas",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"-Vaya día, aunque ya lo veía venir- dijo Hermes en voz baja mientras caminaba agotado y abría la puerta de un bar de marineros a la orilla del mar.",
    fecha:"Mayo 11, 2025",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/en_busca_de_tormentas.html"
  },
  {
    nombreBlog:"Una página en blanco",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Su café, dijo el mesero con un delantal rojo acercándose a la mesilla fuera del local en una pequeña terraza callejera que se encontraba enmarcada de maseteros con plantas verdes que contrastaban entre luz y sombra por la tarde.",
    fecha:"Abril 27, 2025",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/una_pagina_en_blanco.html"
  },
  {
    nombreBlog:"Una Victoria Perdida",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¡Todos en sus posiciones! Exclamo el príncipe Enzo montando un fuerte y brioso caballo negro de batalla. ¡El enemigo se prepara frente a nosotros, demostrémosle de que están hechos los soldados del reino de Pladio!",
    fecha:"Septiembre 23, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/una_victoria_perdida.html"
  },
  {
    nombreBlog:"Un Futuro Perfecto",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¡Por aquí Elise! La joven medica de veintiséis años agitaba una mano en el aire mientras que con la otra atendía a un soldado que había recibido una herida durante uno de los entrenamientos.",
    fecha:"Septiembre 09, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/un_futuro_perfecto.html"
  },
  {
    nombreBlog:"La Ultima Rosa",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Alcanzando el objetivo en cuarenta y cinco segundos, la hermosa chica de cabello rojo brillante cerraba el visor de su casco y se acercaba a orilla de la cima de uno de los rascacielos más altos de la ciudad, preparándome para el asalto solicito confirmación.",
    fecha:"Septiembre 02, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_ultima_rosa.html"
  },
  {
    nombreBlog:"Gizli Capítulo 4",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Buen trabajo Dunnam, Kenneth miraba Evan quien estaba en brazos de su madre mientras que un paramédico intentaba revisarlo en la ambulancia no muy lejos de donde se encontraban ellos.",
    fecha:"Agosto 26, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/gizli_capítulo_4.html"
  },
  {
    nombreBlog:"Gizli Capítulo 3",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Dunnam revisaba las fotos del área donde encontraron a Sam mientras que Kenneth preparaba su reporte para dar como terminado el caso de la desaparición de la señora Samanta y su compañera de trabajo Isabel.",
    fecha:"Agosto 19, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/gizli_capítulo_3.html"
  },
  {
    nombreBlog:"Gizli Capítulo 2",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Ya revisamos todo el edificio y no hay rastro de Evan, la bicicleta es todo lo que hay detective. Dijo el policía que le entregaba una carpeta con todas las fotografías y resultados de la búsqueda al detective Kenneth.",
    fecha:"Agosto 12, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/gizli_capítulo_2.html"
  },
  {
    nombreBlog:"Gizli Capítulo 1",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Buen día Kenneth, saludó Dunnam a su compañero que estaba bebiendo un café en su escritorio mientras revisaba sus correos temprano por la mañana.",
    fecha:"Agosto 05, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/gizli_capítulo_1.html"
  },
  {
    nombreBlog:"Crónicas de una Inmortal Parte 3",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¡Maldito infeliz como te atreves a acusar a la señorita Philipa de esa manera! Alzó la voz uno de los habitantes del pueblo tomando a Collins del cuello y levantándolo con fuerza.",
    fecha:"Julio 29, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/cronicas_de_una_inmortal_3.html"
  },
  {
    nombreBlog:"Crónicas de una Inmortal Parte 2",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Collins se encontraba acarreando agua del arrollo cerca de su casa junto a las ruinas del molino en un día muy caluroso por lo que sudaba constantemente por el esfuerzo extra que representaba el hacer ese tipo de esfuerzo con un solo brazo. Una vez que las vasijas de agua estuvieron llenas bebió un poco de agua directamente del rio mojando toda su camisa que después se retiro revelando las quemaduras en su pecho y espalda provenientes de su brazo faltante.",
    fecha:"Julio 22, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/cronicas_de_una_inmortal_2.html"
  },
  {
    nombreBlog:"Crónicas de una Inmortal Parte 1",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Vamos muchacho te falta un brazo no una pierna, dijo el grande y robusto panadero que empujaba al joven de cabello negro que caminaba lo mas rápido que podía mientras balanceaba un enorme costal de harina con su brazo izquierdo.",
    fecha:"Julio 15, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/cronicas_de_una_inmortal_1.html"
  },
  {
    nombreBlog:"La Fantasía de Nule",
    imagenBlog:"https://lh3.googleusercontent.com/rtQDRUu5FaoIwYRLynKF3gBwWBBi4wKYGc4Gc4_DEe7fafTYn9aqBxQBW81RJGUYT556YptUsdSZxX8QUOLUCsbHFnxs7ES1MVQ270zXFo30f_45MPL-XUTyIx3hqxruQJu-zKI5=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Esto es triste, se quejaba Yori mientras estaba sentada junto a su amiga Nule en una banca a la sombra de un árbol comiendo una paleta helada de chocolate.",
    fecha:"Julio 13, 2020",
    tipo:"Pelicula",
    titulo:"Amor de Gata",
    capitulo:"none",
    tiempo:"Min. 5:10 - 7:21",
    link:"peliculas/la_fantasia_de_nule.html"
  },
  {
    nombreBlog:"El Dilema de los Oficiales Summer y Dunn",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Como odio el turno nocturno, decía Summer mientras bostezaba en el asiento del copiloto dentro de la patrulla.",
    fecha:"Julio 08, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_dilema_de_los_oficiales_summer_y_dunn.html"
  },
  {
    nombreBlog:"El Reto de Quetzalcóatl",
    imagenBlog:"https://lh3.googleusercontent.com/N_d3aPne_1b61YCWQQBhhE-gd8hTm9JQfFM85kz-gFxCnbCf60vPUB1NaJlD6c1E3H9qyj1Ln0XfetLsOcIULc32Jii-53uK1ZSk1DZVVSxbB6XBPuWVR04-_e58tawSOp663unc=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La pelea estaba alcanzando su punto mas álgido mientras que Mash bloqueaba la potente patada de la diosa Quetzalcóatl con su escudo lo que la lanzo varias decenas de metros hacia atrás resistiendo el enorme poder de la diosa.",
    fecha:"Julio 06, 2020",
    tipo:"Serie",
    titulo:"Fate Grand Order",
    capitulo:"Capitulo: 11",
    tiempo:"Min. 7:10 - 9:21",
    link:"series/el_reto_de_quetzalcoatl.html"
  },
  {
    nombreBlog:"Los Gólems y la Hechicera",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La hermosa hechicera Amal se encontraba viajando de noche en el bosque del norte. Su vestido verde esmeralda destellaba sutilmente en la oscuridad mientras que su báculo meticulosamente tallado y con adornos de oro con una gran piedra azul en la punta iluminaba su camino tenuemente en la oscuridad. Mientras que su cabello largo y violeta caía sobre el preocupado rostro de la hechicera.",
    fecha:"Julio 01, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/los_golems_y_la_hechicera.html"
  },
  {
    nombreBlog:"El Mundo de Dioses y Humanos",
    imagenBlog:"https://lh3.googleusercontent.com/A1ztVHB_X5vul62dPzXvjw2T51RCwwsUpt1o2upVqdTLQrPCSuBS06r-ls3wDFKJ80iwFmzTqSH1958GPQNK9plT1k0dfs0pRcXXcU00JhUcOj6hMzrrNecfas8QoibfSfQPl4UX=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El fuego chisporroteaba en la hoguera bajo la noche estrellada. Fujimaru montaba guardia mientras que todos sus compañeros descansaban antes de continuar su viaje de regreso a Mesopotamia.",
    fecha:"Junio 29, 2020",
    tipo:"Serie",
    titulo:"Fate Grand Order",
    capitulo:"Capitulo: 9",
    tiempo:"Min. 17:30 - 22:18",
    link:"series/el_mundo_de_dioses_y_humanos.html",
  },
  {
    nombreBlog:"Beber, Comer, Cantar, Bailar",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Beber, comer, cantar, bailar ya ni siquiera recuerdo cuantas veces he presenciado esta historia y aun menos conozco la cantidad de escritores que han reescrito estas palabras en sus historias nuevas.",
    fecha:"Junio 24, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/beber_comer_cantar_bailar.html"
  },
  {
    nombreBlog:"La Gorgona Indestructible",
    imagenBlog:"https://lh3.googleusercontent.com/rzBuAvDR7AgmIcs74mcRckKqYxo9bWOvzNWBgGNXaeVWka-mnNVdwAbMdVnJ65lJvgVyZ5Xq6Pmy_H3dks_7fIXLU8L8bAbqocJDH6eJpLH3eMj548hTBJ5vf2nQmBi8wz5_3DlD=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Toda la llanura se encontraba de color gris tras el ultimo ataque de petrificación masiva de Gorgon, el viento era lo único que se podía escuchar en lo que hasta hace unos momentos era un infernal campo de batalla.",
    fecha:"Junio 22, 2020",
    tipo:"Serie",
    titulo:"Fate Grand Order",
    capitulo:"Capitulo: 8",
    tiempo:"Min. 10:40 - 13:10",
    link:"series/la_gorgona_indestructible.html"
  },
  {
    nombreBlog:"La Chica que Conoció Irene",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El pequeño bote de remos en el que navegaba Irene golpeó contra la orilla del pequeño lago ya bastante entrada la noche despertando a la joven que se había quedado dormida con la caña de pescar entre sus manos.",
    fecha:"Junio 17, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_chica_que_conocio_irene.html"
  },
  {
    nombreBlog:"La Leyenda de la Chica Sol",
    imagenBlog:"https://lh3.googleusercontent.com/kdGZkhxzzlGrNJYvCg7SpQB8mNhlHw9rHCmuWn5vmH1qtD7nLXlVSfc6TySqor844-MIPACezThN4OgKIX1eDWxCxFb4ozwUIdVQJLuLNILiPIwNx6ESGJdiNYgS2HvAYOj2koMw=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Mucho tiempo sin vernos chico. Dijo Kei, un hombre de unos treinta años que llegaba al pequeño sótano cargado con una bolsa de comida del minisúper en una mano y una cerveza en la otra ¿has perdido peso?",
    fecha:"Junio 15, 2020",
    tipo:"Pelicula",
    titulo:"Tenki no Ko",
    capitulo:"none",
    tiempo:"Min. 15:00 - 17:00",
    link:"peliculas/la_leyenda_de_la_chica_sol.html"
  },
  {
    nombreBlog:"Una Nueva Oferta para Melisa",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La presentación casi había terminado y casi todo había salido como lo había planeado Melissa.",
    fecha:"Junio 10, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/una_nueva_oferta_para_melisa.html"
  },
  {
    nombreBlog:"¡Elegimos estar aquí!",
    imagenBlog:"https://lh3.googleusercontent.com/u2XaxmjjbilJ6iep3xJOZPkH2ztYmZfZITDyl2BRAZp4Fd1wGOhNwL7DUM5PMv1vhcWmU8kJwBqRFi2-r7BHfReCyAJHAMxUJqmEdmi4AWn0__ugAhLHB-63wdAjxn8Rfw6DA_5f=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El rompe hielos se mecía continuamente durante la noche. Los pasillos del gran buque eran iluminados por la tenue luz de emergencia roja proyectando pequeñas sombras. Las olas envestían con fuerza el casco de la nave hasta saltar sobre la cubierta. La tripulación que dirigía el enorme barco se sujetaba como podía dentro del puente de mando sin dejar de dirigir la nave.",
    fecha:"Junio 08, 2020",
    tipo:"Serie",
    titulo:"Sora Yori mo Tooi Basho",
    capitulo:"Capitulo: 8",
    tiempo:"Min. 16:00 - 20:10",
    link:"series/elegimos_estar_aqui.html"
  },
  {
    nombreBlog:"Dichos de viejos",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Bueno tengo que admitir que venir a este lugar no fue tan mala idea, dijo Fore mientras caminaba tambaleándose un poco bebiendo de su botella.",
    fecha:"Junio 08, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/dichos_de_viejos.html",
  },
  {
    nombreBlog:"¡Tenemos que ir!",
    imagenBlog:"https://lh3.googleusercontent.com/2e4LmmkVAD0FVDF4SQpudBfu6C4UJeJuOx2zV8V6JNOdD3-i5n3cNhepL5zdQaFt1M4hYtd87EpVvYYy9AdgggMi_XVccR2r30n6IamxftLhpbUQT8z4flAocpVGbQs6A_2wb4q7=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Las cuatro chicas dormían en la casa de campaña en la mitad de la montaña mientras el viento frio soplaba afuera llenando todo el paisaje de una suave neblina. Mari quien dormía como si el espacio no fuera un problema despertó y se sentó una adormilada dentro de su bolsa de dormir. Después de unos minutos abrió el cierre de la casa de acampar y asomo su cabeza fuera de esta.",
    fecha:"Junio 01, 2020",
    tipo:"Serie",
    titulo:"Sora Yori mo Tooi Basho",
    capitulo:"Capitulo: 4",
    tiempo:"Min. 19:10 - 22:00",
    link:"series/tenemos_que_ir.html"
  },
  {
    nombreBlog:"Me has Dado mi Venganza",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Te dije que traerlo aquí era una mala idea, dijo Isabel corriendo lo mas rápido que podía detrás de Noki.",
    fecha:"Mayo 27, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/me_has_dado_mi_venganza.html"
  },
  {
    nombreBlog:"¡Saldré de Viaje sin un Plan!",
    imagenBlog:"https://lh3.googleusercontent.com/3mLZL_P7ie4_Lp-rWPilDbCgSxGSXqwkhHXvPDWcolaU6eI-nqpJ6bdjFfW2F483ukrkW1oXK06N6_l5Szo0JVzv6XuyyUL8GDHLY2H5H8Efg36mQUJlihwzxgWW5f5OUdeHTfom=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El profesor de ingles se acerco tranquilamente desde atrás y cerrando el libro que llevaba en su mano golpeo la cabeza Mari por hablar en clase.",
    fecha:"Mayo 25, 2020",
    tipo:"Serie",
    titulo:"Sora Yori mo Tooi Basho",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 4:17 - 7:30",
    link:"series/saldre_de_viaje_sin_un_plan.html"
  },
  {
    nombreBlog:"La Ejecución de un Rey",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La plaza estaba al borde de reventar, era una plaza de varias decenas de metros de largo y justo en el centro se había montado un entarimado de aproximadamente 3 metros de alto en donde se encontraban parados de manera muy solemne cerca de quince personas en espera de que algo sucediera.",
    fecha:"Mayo 20, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_ejecucion_de_un_rey.html"
  },
  {
    nombreBlog:"El Hibiol de Maquia",
    imagenBlog:"https://lh3.googleusercontent.com/wsc3xKw8ECf1ESXOCP1QK6Yc0_2b5x_c0gplCXXtOqw77egaaAKRcRjeWym3kfFfJ3MGAIrclhpS3gfTmgIIdBCViCNvLzp8WcxbPpmPL8Lkz1WuNRarBeqUyYDjuPYaR5JkCgOK=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Los insectos del bosque era lo único que se podía escuchar en la oscura noche que casi llegaba a su fin, entre todos estos sonidos se podían escuchar los débiles pasos de Maquia quien acababa de perder su hogar a manos de soldados humanos.",
    fecha:"Mayo 18, 2020",
    tipo:"Pelicula",
    titulo:"Maquia",
    capitulo:"none",
    tiempo:"Min. 13:00 - 16:05",
    link:"peliculas/el_hibiol_de_maquia.html"
  },
  {
    nombreBlog:"Un Viaje que Termina",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Pam y Ana caminaban por la vereda que descendía lentamente por el bosque hasta la pequeña ciudad en el que ellas habían crecido, sus mochilas ya no eran tan grandes como lo habían llegado a ser en algunos momentos de su viaje pero aun así se movían un poco mas lento debido a ellas.",
    fecha:"Mayo 13, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/un_viaje_que_termina.html"
  },
  {
    nombreBlog:"La Declaración de Sonezaki San",
    imagenBlog:"https://lh3.googleusercontent.com/uiDhQBbavbiU2qD40vGNCwTLfaITEzJ8NNWo0ME4zatSc2aNp8BSdqyNpm_bIn9PIwuWyd-qUATzMDvunXaAtH-IE6n_oX2lwyBzWti3XN_yN_FXtkdVt4t1av8NUPEXekXT4BVJ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Sonezaki san caminaba decididamente cruzando el patio de la escuela hasta donde se encontraba Amagi junto a la fogata que marcaba el final del festival.",
    fecha:"Mayo 11, 2020",
    tipo:"Serie",
    titulo:"Araburu Kisetsu No Otomedomo Yo",
    capitulo:"Capitulo: 8",
    tiempo:"Min. 18:03 - 19:10",
    link:"series/la_declaracion_de_sonezaki_san.html"
  },
  {
    nombreBlog:"El Día Lluvioso de Andrea",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La pequeña Andrea se encontraba jugando con sus muñecas en el jardín trasero de su casa cuando una pequeña brisa salpico su rostro lo que la hizo sonreír alegremente. La pequeña froto sus manos en su rostro mientras miraba a su alrededor buscando a la persona que la había mojado.",
    fecha:"Mayo 06, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_dia_lluvioso_de_andrea.html"
  },
  {
    nombreBlog:"La Declaración de Amagi",
    imagenBlog:"https://lh3.googleusercontent.com/G7KwmwkBCtf-HvENT0nHbDItLl20VmVIhFUEMJRMn658vof4Tj7-RBggHIbFglrx23GqQRcM1D4Qc8zcnqDdPhX1iNALH2h5-jqoe51EegG-IyAos4fPRlv6Xd1l2himywSmR03t=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Sonezaki subía las escaleras hacia la azotea con paso muy molesto y firme mientras murmuraba para si misma. ¿Qué demonios? En serio, ¿Qué demonios? ¡Lo dicen cuando no cambio mi aspecto y lo dicen cuando lo hago! la chica tiro de la puerta corrediza pero esta no abrió por lo que intento tirar mas fuerte hasta el punto de inclinar todo su cuerpo para intentar abrir la puerta. Finalmente se rindió agachándose sobre sus rodillas y abrazándolas. Que demonios...",
    fecha:"Mayo 04, 2020",
    tipo:"Serie",
    titulo:"Araburu Kisetsu No Otomedomo Yo",
    capitulo:"Capitulo: 4",
    tiempo:"Min. 2:44 - 4:10",
    link:"series/la_declaracion_de_amagi.html"
  },
  {
    nombreBlog:"El Día que el Dragón Anciano Llegó",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Y donde están los refuerzos? Preguntaba Azir desesperado mientras colocaba un cargador nuevo en su arma y regresaba a su posición en la trinchera vaciado el cargador en ráfagas que eran prácticamente inaudibles debido al la gran cantidad de explosiones y ráfagas de disparos de los demás sobrevivientes en la trinchera.",
    fecha:"Abril 29, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_dia_que_el_dragón_anciano_llego.html"
  },
  {
    nombreBlog:"Coqueteo en la Pila del Agua",
    imagenBlog:"https://lh3.googleusercontent.com/9j6iBbh3a76CYp-e-ATf0CdTshp09qzZc2cGejIBpVMQWAIo4wEmmU2Ze5YzLEbq6om4ypDzHBgO8do3yEHwUaszElsn3zYRb4aBsIR9WJF2LPtCpRHHXziag-yeV9CUrrsM5r-F=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Sonezaki miraba con detenimiento a la pila del agua ignorando a Amagi cuando se dio cuenta que este la miraba muy de cerca.",
    fecha:"Abril 27, 2020",
    tipo:"Serie",
    titulo:"Araburu Kisetsu No Otomedomo Yo",
    capitulo:"Capitulo: 2",
    tiempo:"Min. 10:50 - 11:50",
    link:"series/coqueteo_en_la_pila_del_agua.html"
  },
  {
    nombreBlog:"La Chica Errante",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Otro mundo lleno de vida dijo la chica de piel morena en voz baja mientras tomaba su taza de café y tomaba un sorbo de manera muy elegante haciendo que varios de los meseros que atendían el lugar desviaran la mirada hacia ella.",
    fecha:"Abril 22, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_chica_errante.html"
  },
  {
    nombreBlog:"La Horquilla de Jade",
    imagenBlog:"https://lh3.googleusercontent.com/aqDRGxXA-fuOBI2_Uib2VfWpx89drpJSMqF7QkMYMyduvAi5VdeR-ChRPpNUWbXafuAd0HIcBn9AINdI-Xq9wksc8y6LbGfuWhyzbUMZSECv9A9H2QXkKV1AVGsNbij7NJ5cYMVg=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Suzhen, Xu Xian y su perro Dudou por fin habían llegado al Taller de Jade Precioso, lugar en donde podrían descubrir el origen de la horquilla de jade de la joven Suzhen y quizás así saber un poco mas sobre su pasado olvidado.",
    fecha:"Abril 20, 2020",
    tipo:"Pelicula",
    titulo:"White Snake",
    capitulo:"none",
    tiempo:"Min. 33:41 - 38:10",
    link:"peliculas/la_horquilla_de_jade.html"
  },
  {
    nombreBlog:"Fábrica de Monstruos",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Albert aquí están los resultados de las pruebas que pediste hace un par de días, dijo Pedro entregándole una carpeta llena de hojas con graficas y métricas.",
    fecha:"Abril 15, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/fabrica_de_monstruos.html"
  },
  {
    nombreBlog:"Te Presto mi PlayStation",
    imagenBlog:"https://lh3.googleusercontent.com/LgrK8M-Z8n57Dj01V9Ku6jvMvyHb-j-2le9CG0i-DD0oRpinVP2M6Bth3-jQ2H7tyTGBIdiHssccrYBWFL0XJhGKksRkNA-A89H1ZHHfXu8LTqBg9NE-8H82wrJy1aGOmlZsI3QU=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Haruo se sorprendió al ver la gran caja que estaba cargando la chica, Hidaka, ¿Qué pasa con esa PlaySatation, acaso me la darás?",
    fecha:"Abril 13, 2020",
    tipo:"Serie",
    titulo:"Hi Score Girl",
    capitulo:"Capitulo: 12",
    tiempo:"Min. 18:30 - 20:35",
    link:"series/te_presto_mi_playstation.html"
  },
  {
    nombreBlog:"La Puerta en el Estudio",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Muy bien señora Sánchez ya solo queda entrégale la llave de la entrada principal y una carta del dueño anterior, dijo la vendedora de bienes raíces mientras recogía los papeles recién firmados y le entregaba una llave y una carta sellada a la señora Sánchez.",
    fecha:"Abril 08, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_puerta_en_el_estudio.html"
  },
  {
    nombreBlog:"Haruo vs Hidaka",
    imagenBlog:"https://lh3.googleusercontent.com/Ujfag-nP3X4C5eZ4huogSn-TbvkIftkXHg3Ry-oVAGfTNE4VH29b9ehpt1mTkmkBkRXHG2lXolJSi51Y2HUuBgAs2jyrWnMTo_vIVynG2b290r5BeQvGcmd7Pw1uCQw2eMYtxUkQ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Yaguchi-kun, Yaguchi-kun, llamaba Hidaka al ver a Haruo Yaguchi observando absorto el arcade, ¿Qué haces mirando los alrededores?",
    fecha:"Abril 06, 2020",
    tipo:"Serie",
    titulo:"Hi Score Girl",
    capitulo:"Capitulo: 10",
    tiempo:"Min. 5:40 - 9:00",
    link:"series/haruo_vs_hidaka.html"
  },
  {
    nombreBlog:"Asalto en la Bodega",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Qué tenemos aquí agente Rain?, preguntó el detective mientras entraba a la bodega en donde decenas de cadáveres se encontraban regados por todo el lugar.",
    fecha:"Abril 01, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/asalto_en_la_bodega.html"
  },
  {
    nombreBlog:"Guile vs Zangief",
    imagenBlog:"https://lh3.googleusercontent.com/H3Rd6Fl8NCYVRKD_T19Y-8dZvVNaXSzDr0t9rxsa6CCF9c4vB8oARZNnAA3-FlSjn7eSlZy8UwB1tUyIFNlwIKthfeFCd1dqocRqdvkI9N_6bjY7-mQSYGoK8J77dr3Ur8I-hJ5G=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Haruo estaba decidido a jugar la revancha en Street Figther II después de que el anterior jugador en la fila fue derrotado por la misma chica.",
    fecha:"Marzo 30, 2020",
    tipo:"Serie",
    titulo:"Hi Score Girl",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 3:10 - 8:20",
    link:"series/guile_vs_zangief.html"
  },
  {
    nombreBlog:"Los Ogros Ríen Cuando Hablas del Próximo Año",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Entonces te gustaría escuchar mi plan para el próximo año mientras esperamos? Preguntó el chico mientras veía a la chica de pelo verde sentada junto a el en la banca del parque.",
    fecha:"Marzo 25, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/los_ogros_rien_cuando_hablas_del_proximo_año.html"
  },
  {
    nombreBlog:"El Corazón de Luca",
    imagenBlog:"https://lh3.googleusercontent.com/lg6wHLa-eVBv3QCxs4PTL6BKUlqrmixRS7TSJCPhfEvD-fJDA57FGatKy7paFVPQCZYPu7VltsNVXPzGY-wLqbHcmS0awnEerLD7x5YXkd_6midwp0w5BD5BJ-WJVNBxmSSwbaKh=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Que?¿Has perdido el juicio? Preguntaba Bianca en voz alta acercándose de forma controladora sobre Luca ¿Cómo pudiste ser tan estúpido? Solo un idiota dejaría a una mujer así.",
    fecha:"Marzo 23, 2020",
    tipo:"Pelicula",
    titulo:"Dragon Quest Your Story",
    capitulo:"none",
    tiempo:"Min. 48:22 - 50:15",
    link:"peliculas/el_corazon_de_luca.html"
  },
  {
    nombreBlog:"El Ataque a Media Noche",
    imagenBlog:"https://lh3.googleusercontent.com/Z2hj84sbg5nDAkupFKYAbSM5ckxZPazlT-ZoqiFUsQo-eE8Vhymy7qzi-MSxpR5t_wpBX8_J3JdOLQYk5pSn5nFaBnFWgE84w6eUM2pExwhoRgBklF3YxV-PICKdnGpztrXS_XdK=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Violet cayo al suelo junto con el comandante mientras la sangre brotaba de lo que quedaba de su brazo derecho.",
    fecha:"Marzo 16, 2020",
    tipo:"Serie",
    titulo:"Violet Evergarden",
    capitulo:"Capitulo: 9",
    tiempo:"Min. 1:00 - 3:05",
    link:"series/el_ataque_a_media_noche.html"
  },
  {
    nombreBlog:"Expreso al Infierno",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Nicolás despertó sobresaltado al percibir el golpeteo de las vías del tren durante su marcha haciendo que otro de los pasajeros del vagón le prestara atención.",
    fecha:"Marzo 11, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/expreso_al_infierno.html"
  },
  {
    nombreBlog:"Una Carta Difícil",
    imagenBlog:"https://lh3.googleusercontent.com/sM4wHg0DismR5bfSm288JvRSraJhseYb2MDGkP3znq7CEjX8tK7Ozozh1HpTtixna26sC17V2n7Olo31O-phwKFtaLC-Vj75xbf1ZJwAXVnCnE2onSOXqyB35X9jicfDLT1VA9L-=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Violet se encontraba de pie en el rincón de la oficina mirando la pared como si fuese una niña pequeña a quien hubiesen castigado por su mal comportamiento cuando Erica e Iris entraron.",
    fecha:"Marzo 09, 2020",
    tipo:"Serie",
    titulo:"Violet Evergarden",
    capitulo:"Capitulo Especial",
    tiempo:"Min. 9:45 - 11:00",
    link:"series/una_carta_dificil.html"
  },
  {
    nombreBlog:"El Hombre de la Banca Junto al Río",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El hombre se encontraba sentado en una banca junto a río mientras el sol se ponía por la tarde. Era una vista espectacular de la torre Eiffel aquel día, había un poco de nubes pero estas contrastaban perfectamente con el anaranjado del cielo, así que decidí sentarme junto a aquel hombre ese día sin imaginar la asombrosa historia que estaba apunto de escuchar a la orilla del río Sena.",
    fecha:"Marzo 04, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_hombre_de_la_banca_junto_al_río.html"
  },
  {
    nombreBlog:"¿He escrito una buena carta?",
    imagenBlog:"https://lh3.googleusercontent.com/rtfB1eco1VSU6qQKrHvBEC5umOUK0ystmC5tOWPTHz_daPCEY-7_LU1AGThr_q7TZRhlIo9HKIkBOM8TIlIhOizPVtAYxdSmnkc5qVYTLN945Wez3MX8IHBo5AX5y_7NLxEdZzYU0Q=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Iris estaba sentada en una banca en el interior del tren mientras observaba por la ventanilla sosteniendo el ramillete de flores azules que sus padres le habían obsequiado como regalo de despedida. Mientras el tren comenzaba a caminar de regreso a su ciudad Violet le hizo una pregunta.",
    fecha:"Marzo 02, 2020",
    tipo:"Serie",
    titulo:"Violet Evergarden",
    capitulo:"Capitulo: 4",
    tiempo:"Min. 20:15 - 21:23",
    link:"series/he_escrito_una_buena_carta.html"
  },
  {
    nombreBlog:"Marauder el Asesino de Espadas",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Cómo rayos es tan fuerte?, Ronin se limpiaba el sudor de la frente con la manga de su camisa mientras su brazo temblaba. Éramos 6 caza recompensas contra el y ya logro matar a dos.",
    fecha:"Febrero 26, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/marauder_el_asesino_de_espadas.html"
  },
  {
    nombreBlog:"La Heredera del Clan Isurugi",
    imagenBlog:"https://lh3.googleusercontent.com/kIw24evx6oLZepSQ48pQEbHLCpoNEBHVDlzZ-Iad0sFLqwPNKeM29DdSOh5uyMt9JEBomiiwH-7uKxRmbStaP0P-dCDi4gnVvRyqsYSy1tauZqb9y_0zrRAEgU1gzSngZaJFbTtL=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Rikka caminaba por el laboratorio en ruinas de su padre cuando una pequeña caja sobre una mesa llamo su atención. Cuando la abrió una lente en la base del aparato comenzó emitir luces de colores que tomaron forma hasta comenzar a reproducir un video holográfico dejado por su abuelo y su padre.",
    fecha:"Febrero 24, 2020",
    tipo:"Pelicula",
    titulo:"BlackFox",
    capitulo:"none",
    tiempo:"Min. 69:47 - 72:50",
    link:"peliculas/la_heredera_del_clan_isurugi.html"
  },
  {
    nombreBlog:"Los viajes de Caronte",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Aun no se como es que llegue aquí, el hombre mayor se encontraba haciendo fila junto a un rio si saber muy bien porque estaba ahí. No puedo recordar bien lo que paso además de que llevo meses haciendo esta maldita fila.",
    fecha:"Febrero 19, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/los_viajes_de_caronte.html"
  },
  {
    nombreBlog:"Los Recuerdos de Ray",
    imagenBlog:"https://lh3.googleusercontent.com/t3HT_Tc3Jcib1BG0XaO4CnjFKKUje6qSykwb2JXRDFCNEKpGIlePsFPwU3YJ6TqZ0sot9rDeNW4jQISlMPVMceKkHECXBnTJTW8TVnC9p_kkJLOLwqNCIcTtE7zW3_irPgMaO8QpEA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Ray, Emma y Norman se encontraban en la enfermería que era iluminada con los últimos rayos del sol de aquel día, Emma se encontraba sentada en la cama mientras que Norman se encontraba sentado en un banquillo junto a la cama.",
    fecha:"Febrero 17, 2020",
    tipo:"Serie",
    titulo:"Yakusoku no Neverland",
    capitulo:"Capitulo: 9",
    tiempo:"Min. 12:29 - 15:50",
    link:"series/los_recuerdos_de_ray.html"
  },
  {
    nombreBlog:"La Chica del Centro Comercial",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Otro día mas trabajando en este centro comercial, pensaba Lucas mientras caminaba distraído deslizando su dedo sobre la pantalla de su celular viendo las novedades que publicaban sus amigos. Trabajar en un centro comercial no es tan divertido como yo pensaba que seria, pensaba mientras subía las escaleras eléctricas que lo llevaban al tercer piso en donde se encontraba la tienda de la que el era gerente.",
    fecha:"Febrero 12, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_chica_del_centro_comercial.html"
  },
  {
    nombreBlog:"El Reloj de Krone",
    imagenBlog:"https://lh3.googleusercontent.com/oOVTIFiIksOFjw8aR94subPgmnIzX3irclbv1XNEw_k5mcAOzZoxLUuIoOuUm8Ez6SrdpNaqv0ew_EbO3igoMWagT3Jaf4zrojIWbRR__Y8hjK-6F39vfEo259VhzCFIy0bLIHja2Q=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Norman y Emma habían decidido aceptar el trato con la hermana Krone quien los recibió en su habitación ya bastante avanzada la noche.",
    fecha:"Febrero 10, 2020",
    tipo:"Serie",
    titulo:"Yakusoku no Neverland",
    capitulo:"Capitulo: 7",
    tiempo:"Min. 8:33 - 12:35",
    link:"series/el_reloj_de_krone.html"
  },
  {
    nombreBlog:"Crímenes Contra el Ciclo de la Vida",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El juez se encontraba en su asiento dirigiendo el caso del hombre que tenia enfrente mientras que la sala se encontraba abarrotada de hombres y mujeres que escuchaban haciendo ademanes de negación ante los crímenes del señor Lister.",
    fecha:"Febrero 05, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/crímenes_contra_el_ciclo_de_la_vida.html"
  },
  {
    nombreBlog:"El Conejo de Conny",
    imagenBlog:"https://lh3.googleusercontent.com/c7bxFkqxsX-xXfZnc48Bi4CfkVVmh_AzFBTGDrSDaMYGhtSgD38j6PwFpkBojlA0U1OgvKtHyfgorDQixdpZ2r1hX-GzGJUGM5a8gjji-HfKGgVo9fIXwlLH-0Srl1EQg7x6D5xHRA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Norman y Emma habían llegado hasta la entrada del orfanato en busca de su pequeña amiga Conny quien había olvidado su conejo de peluche antes de ir a su nuevo hogar. La entrada era como un callejón tenuemente iluminado por algunas lamparas cerca de un par de puertas altas a cada lado de los muros, cerca de estas puertas había un camión estacionado no muy lejos de donde los pequeños se encontraban.",
    fecha:"Febrero 03, 2020",
    tipo:"Serie",
    titulo:"Yakusoku no Neverland",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 15:25 - 18:41",
    link:"series/el_conejo_de_conny.html"
  },
  {
    nombreBlog:"La Ira de Apolo",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Los tres poderosos ciclopes hijos de Gaia y Uranos, Apolo caminaba lentamente mirando con repudio a los tres poderosos ciclopes postrados en el suelo con las piernas totalmente atravesadas por cientos de las flechas doradas de Apolo.",
    fecha:"Enero 29, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_ira_de_apolo.html"
  },
  {
    nombreBlog:"El Día que Kaguya Ganó",
    imagenBlog:"https://lh3.googleusercontent.com/LvNo4eVN64-k76XF6wc5dWvinH7bbcCDGtrvH1sq-VtJpy6-DNUef258aN1pK3WBAtJq0DsW1S23Td7ptZNhi03E7u3CH6m_BoyLJV-SduOf8sOXu7GCPq9bT0itQOH1xdKnXQrHXg=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Shinomiya se encontraba sollozando debajo de una escalera en un callejón de la ciudad mientras pensaba en todos sus amigos quienes debieron de haber disfrutado los fuegos artificiales sin ella.",
    fecha:"Enero 27, 2020",
    tipo:"Serie",
    titulo:"Kaguya-sama wa Kokurasetai",
    capitulo:"Capitulo: 12",
    tiempo:"Min. 10:45 - 14:18",
    link:"series/el_dia_que_kaguya_gano.html"
  },
  {
    nombreBlog:"¡Adivinemos Donde Estamos!",
    imagenBlog:"https://lh3.googleusercontent.com/Kpk5H00oBFJYtz-iMkQbycAJPXk9iRq6FjL0nRSoUEhmmLd-MBQfbiH0fhpxMLDYg1Wfdacq0KZyhfaX1Lqm0ZAZ_iA69FyUx6pmz2rz4Z-3-djwmiunoaOy8ckgpQfKzQvh8NJcjg=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    fecha:"Enero 20, 2020",
    tipo:"Serie",
    titulo:"Yuru Camp",
    capitulo:"Capitulo: 12",
    tiempo:"Min. 21:58 - 23:03",
    link:"series/adivinemos_donde_estamos.html"
  },
  {
    nombreBlog:"Las Cadenas del Tártaro",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¿Y bien como demonios ocurrió esto? Un oficial de alto grado militar veía como unas enormes cadenas estaban totalmente destrozadas en el piso de las gran cueva.",
    fecha:"Enero 18, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/las_cadenas_del_tartaro.html"
  },

  {
    nombreBlog:"Un Dia de Mucho Trabajo en la Morgue",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Rayos voy algo tarde para el trabajo, pensaba Steven mientras caminaba por los pasillos de la morgue en la que trabajaba.",
    fecha:"Enero 15, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/un_dia_de_mucho_trabajo_en_la_morgue.html"
  },
  {
    nombreBlog:"Dos Campistas Mensajeando",
    imagenBlog:"https://lh3.googleusercontent.com/zza7a9id6TmNSXr1dPLoRGoJQito7T6KOkcx2_tbB3QgwtGPtqw_ca5N2hcAdZeyMHHxNp1NVhX4Hy7ndD1ret3azfnl_HtpqtDV7ZtsNZ58bwJY1F7dcrm39vZVnPgN1KDgZ6hu6g=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud",
    fecha:"Enero 13, 2020",
    tipo:"Serie",
    titulo:"Yuru Camp",
    capitulo:"Capitulo: 5",
    tiempo:"Min. 17:30 - 21:00",
    link:"series/dos_campistas_mensajeando.html"
  },
  {
    nombreBlog:"El Desafío del Dragón Fafnir",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El enano Mimir llevaba semanas golpeando los fragmentos de una espada que llevo de regreso a la fragua mientras el herrero de Nidavellir limpiaba el sudor de su frente con un pañuelo y veía como el joven Sigfrido continuaba con su entrenamiento arduamente en dirección de la cueva que se encontraba no muy lejos de su taller.",
    fecha:"Enero 08, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_desafío_del_dragon_fafnir.html"
  },
  {
    nombreBlog:"La Chica del Estacionamiento",
    imagenBlog:"https://lh3.googleusercontent.com/pqUoftvGslZPznx_HFLB2gVhE5aeXOsoPF3HhyVOZUt90T1DFvWcFBSfTXZZmI2S4uBR6-aJYszOwvjO___-r7aAwTY22tmr6LZd7ktoGfBdZ6Icgxl3Mu4tgPPeqmIPUT9alK0XXw=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Rin salía del baño para mujeres que se encontraba a unas cuadras de distancia de donde se encontraba acampando aquel día. Sostenía su lampara por el asa para iluminar el lugar mientras pensaba en la chica pelirosa que había visto durmiendo en el suelo del estacionamiento durante el día.",
    fecha:"Enero 06, 2020",
    tipo:"Serie",
    titulo:"Yuru Camp",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 12:30 - 14:15",
    link:"series/la_chica_del_estacionamiento.html"
  },
  {
    nombreBlog:"El Hombre en el Espejo",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Arturo se levantaba todas las mañanas a las 6 de la mañana para comenzar su rutina diaria antes de ir a trabajar. Como todas las personas comunes cuando el despertador comenzaba a timbrar Arturo alzaba el brazo con pesar y lo llevaba hasta la mesilla de noche en donde se encontraba su despertador tirando pequeños golpecillos hasta encontrarlo y lograr apagar el pesado sonido que lo sacaba todas las mañanas de la cama.",
    fecha:"Enero 02, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/el_hombre_en_el_espejo.html"
  },
  {
    nombreBlog:"La Chica que Baila Entre los Arboles",
    imagenBlog:"https://lh3.googleusercontent.com/EZOfRgJKIz9mpDVz3JtTerPlzbbcY1uXV3Dq0xFC8nThtoADBBY50ZywrKuz6rmmqM3yz5GfSEfA8F4GYD4zHQQoLJgCwArGA_2Bq4Jvg91n9xeJ_EeMcLIMTo5UMErzkAWAeUtn=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Era un día como cualquier otro, había salido a caminar al parque como todos los días. Cuando llegue al centro de este y comencé a bajar las escaleras escuche un pequeño tintineo a lo lejos que llamo mi atención. Aun no terminaba de descender todos los escalones cuando la vi bailando entre los arboles no muy lejos de donde yo me encontraba.",
    fecha:"Enero 01, 2020",
    tipo:"Historia Original",
    titulo:"none",
    capitulo:"none",
    tiempo:"none",
    link:"historias_originales/la_chica_que_baila_entre_los_arboles.html"
  },
  {
    nombreBlog:"Yo Hago las Reglas",
    imagenBlog:"https://lh3.googleusercontent.com/rznIr0SgQBuLwpHB1zrdpLmkTsn-YSMNyGEIaUMq6EL7moxs3HBhUUjJBAGIEkL1m65pD4kwsCA0jQzGEsP32_TK2X9XgQURqT3ibajg6OW4SrZlSoZg9KOec_WFUECZkfVCcZF41Q=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Joe corría toda velocidad entre el tráfico en su moto mientras escuchaba el evento de presentación de los finalistas a participar en el gran torneo de Megalonia.",
    fecha:"Diciembre 30, 2019",
    tipo:"Serie",
    titulo:"Megalobox",
    capitulo:"Capitulo 8",
    tiempo:"Min. 18:48 - 22:15",
    link:"series/yo_hago_las_reglas.html"
  },
  {
    nombreBlog:"Tu Eres Quien Controla Este Ring",
    imagenBlog:"https://lh3.googleusercontent.com/OZWxeGJ8AzNdOasZGcwbALKxe9-PQedA-xQovZRSTzEPKx3F5E82oqGysqkOyJljGoGBIeGlxJ66ge4WSleV5LnwpGmWIZ6u7nYpGjQrfWN4Gv18vhoZR0btzJG56aEwKHgALEtEaw=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"¡¿Como que la mayor apuesta de tu vida?! El pequeño Sachio gritaba desesperado sosteniéndose sobre la segunda cuerda en la esquina detrás de Joe, !Nunca llegaran a Megalonia así estafadores!",
    fecha:"Diciembre 23, 2019",
    tipo:"Serie",
    titulo:"Megalobox",
    capitulo:"Capitulo: 4",
    tiempo:"Min. 13:29 - 16:20",
    link:"series/tu_eres_quien_controla_este_ring.html"
  },
  {
    nombreBlog:"Ábrete Paso Hasta Mi Ring",
    imagenBlog:"https://lh3.googleusercontent.com/O17It1AfgRLN-gRY-S7Mcnm6wdGpzD66I5Iq3G9zP25B-vPxTweZzryEOGPj7VWggTVRzxWZtHDrpoI29n25N8YshYiwQ2I-t3eg3KW2MnOs2nK0v6-ikF4wiVICJ0yxc4mnoZOjNQ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"El Reloj sobre el ring marcaba menos de 53 segundos para terminar el primer round, Junk Dog se encontraba frente a Yuri el campeón de Megalobox del momento quien se disponía a pelear con todas sus fuerzas en el siguiente ataque, ambos tenían sus brazos potenciados por sus Gears en posición de guardia preparándose para hacer pedazos a su oponente.",
    fecha:"Diciembre 16, 2019",
    tipo:"Serie",
    titulo:"Megalobox",
    capitulo:"Capitulo: 2",
    tiempo:"Min. 5:48 - 8:55",
    link:"series/abrete_paso_hasta_mi_ring.html"
  },
  {
    nombreBlog:"Los Terrícolas y la Alienígena",
    imagenBlog:"https://lh3.googleusercontent.com/U5TnUgFW22mT6JlONXcGJEYAllbZ3cv4vDuXxZ7OMOhA37wQlyCQhQltfNztdWpm59qoVgxV2JSZ5rUa1iAV8dXYSnE4HYWnWJD1UIKanwFZ6ulnz69Emp_Z7WtkwFAiCEdtSDk_yQ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Kei y Tilarna se encontraban viajando en el auto mientras la lluvia cubría toda la ciudad, Tilarna observaba toda la publicidad política dejada en las calles tras el caos de ese día así como los destrozos que habían dejado las manifestaciones.",
    fecha:"Diciembre 09, 2019",
    tipo:"Serie",
    titulo:"Cop Craft",
    capitulo:"Capitulo: 11",
    tiempo:"Min. 10:45 - 12:42",
    link:"series/los_terricolas_y_la_alienigena.html"
  },
  {
    nombreBlog:"La Fotógrafa y la Alienígena",
    imagenBlog:"https://lh3.googleusercontent.com/Uly2OZCVC3YHvQ4u1a8R1F6Z6xwAH5xYDhOQrJfDiurJhiOsQpbrGX4BpklSI0ue__7iBjIKiOCigYUm0MJBAHA6LpTFvHjouwgsahC-O-MVre-FGqbSOEKXe4hdFaSY7djaiuKpXA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Tilarna se encontraba caminando hacia el auto mientras cargaba un pequeño sándwich en un envoltorio de papel cuando escucha a una chica llamándola.",
    fecha:"Diciembre 02, 2019",
    tipo:"Serie",
    titulo:"Cop Craft",
    capitulo:"Capitulo: 7",
    tiempo:"Min. 6:10 - 9:34",
    link:"series/la_fotografa_y_la_alienigena.html"
  },
  {
    nombreBlog:"El Detective y la Alienígena",
    imagenBlog:"https://lh3.googleusercontent.com/8XD3OsWUIgk4v7Hv0HGByJeXIjH20k4f1gaAbb0u5gr8GVTq1_JBs9MB0ebO-xTUUjuvAWoMA-y9ubjflUt6islOf6l8GdFXV1IpKDxXTyMd2b46pC2Z2mtT9xQ6EfWbRJV6QmQS_A=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Se escuchan tres disparos que hacen resplandecer la ventana de un departamento en un cuarto piso, dentro Kei y Tilarna se encontraban a cubierto detrás de un sofá mientras un sujeto vacía toda una ráfaga de su ametralladora. Cuando se el termina el cargador Kei aprovecha para salir y acertar un par de tiros en el hombre mientras este recargaba.",
    fecha:"Noviembre 25, 2019",
    tipo:"Serie",
    titulo:"Cop Craft",
    capitulo:"Capitulo: 2",
    tiempo:"Min. 00:00 - 4:28",
    link:"series/el_detective_y_la_alienigena.html"
  },
  {
    nombreBlog:"El Tesoro de Nanachi",
    imagenBlog:"https://lh3.googleusercontent.com/jvHmW_vOLUjMyvh9SmTR75oDdqslQ845X08JPEVdLtUo7KfpsCV6_mfzCC3GmDLPmlKaw3jRda7QZrMEFP6h5JCQSqQc-Tmop_TSMjJltH7c3-W5qQz9jF-xuLClFAMBtGORzsMcjA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Nanachi, permíteme preguntarte una cosa, ¿Mitty esta triste al estar junto a ti? Personalmente no creo...",
    fecha:"Noviembre 18, 2019",
    tipo:"Serie",
    titulo:"Made In Abyss",
    capitulo:"Capitulo: 13",
    tiempo:"Min. 24:00 - 26:22",
    link:"series/el_tesoro_de_nanachi.html"
  },
  {
    nombreBlog:"La Fortaleza de los Excavadores",
    imagenBlog:"https://lh3.googleusercontent.com/mZu0mwxo549k1Coisi5eaXVLBchHeIjsXVlbWnFGvXG7FpO24cTxFg-PmyVYvtfLWN-Egut4CNc-y72XUSTX2auydNkkTWmbSqtU4zUtXAsKLAmhrVlr92l1i0yKsaQyX5GKzflsIQ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Una serie de filetes de carne se asaban sobre una roca cubiertos de hierbas aromáticas mientras que Reg los miraba sorprendido.",
    fecha:"Noviembre 11, 2019",
    tipo:"Serie",
    titulo:"Made In Abyss",
    capitulo:"Capitulo: 5",
    tiempo:"Min. 13:09 - 15:14",
    link:"series/la_fortaleza_de_los_excavadores.html"
  },
  {
    nombreBlog:"La Ciudad Alrededor del Abismo",
    imagenBlog:"https://lh3.googleusercontent.com/7qFtauWV_lrsFAR_akXz5jfDq6_gcbXHy1JXkDLMTfU0GI9zcsGlRoKwaBsPzTPqcpfQBOFHz4SvD5P7o02BI7nB__8fnebVS4lGskfQZLv1UYgb7cIr2HueY_-T4boQ3LdOeiVsfA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Una serie de filetes de carne se asaban sobre una roca cubiertos de hierbas aromáticas mientras que Reg los miraba sorprendido.",
    fecha:"Noviembre 04, 2019",
    tipo:"Serie",
    titulo:"Made In Abyss",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 19:11 - 21:00",
    link:"series/la_ciudad_alrededor_del_abismo.html"
  },
  {
    nombreBlog:"La Muñeca y el Lobo Gris",
    imagenBlog:"https://lh3.googleusercontent.com/C5AtRFkVJlF9QDn0HUtzpDYgM04QGGnx0aCZvdjQuNIJcf_iPwDit2spr4DdFuwA7b5eYf0-Tkbt0JdzHHw0d9JrBwbCg4LltecY0aZKsePcO1HBwvogq34nDkeuW_-8OAvPBsk4nA=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Ha pasado mucho tiempo, Cordelia jala con fuerza el velo que cubre su rostro descubriéndolo totalmente, ¡Albert de Blois!",
    fecha:"Octubre 31, 2019",
    tipo:"Serie",
    titulo:"Gosik",
    capitulo:"Capitulo: 23",
    tiempo:"Min. 19:43 - 22:55",
    link:"series/la_muneca_y_el_lobo_gris.html"
  },
  {
    nombreBlog:"La Muñeca y el Caos",
    imagenBlog:"https://lh3.googleusercontent.com/tgyVYobRaYJNw-PBEYuJfQRZIijGTPXglSv3wr2bUpQ7waCUSZ_MWQmvPcet3-2VLyJ2wtrM3bwR68OYWvqKeVH7MqMSPKRdF7Mx5Dt5g59IUO_vxGL_PwgwVIscwJTINSOZWcsf4g=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Repetía Victorique una y otra vez mientras esperaba a que Kujo apareciera en el jardín botánico en el ultimo piso de la biblioteca.",
    fecha:"Octubre 24, 2019",
    tipo:"Serie",
    titulo:"Gosik",
    capitulo:"Capitulo: 9",
    tiempo:"Min. 3:43 - 6:37",
    link:"series/la_muneca_y_el_caos.html"
  },
  {
    nombreBlog:"La Muñeca que Lee el Futuro",
    imagenBlog:"https://lh3.googleusercontent.com/BVb_58nwDq9yNvbfDCKOtY0clGkDCNEBPnqgaFi3CtMhQPSNGlyK7nhMnIovW9cWaNQyGkPEQwTBt-Mtk9So8Vq4GkiXJ9QnE8un3hzoyo1ztydOVhKw-0W0jBbeSVo-NLbPru76Kg=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"La enorme biblioteca tenia varios pisos de altura conectados por una serie de intricadas escaleras que conectaban los múltiples pisos entre si.",
    fecha:"Octubre 21, 2019",
    tipo:"Serie",
    titulo:"Gosik",
    capitulo:"Capitulo: 1",
    tiempo:"Min. 1:00 - 4:35",
    link:"series/la_muneca_que_lee_el_futuro.html"
  },
  {
    nombreBlog:"La Ultima Batalla del Saber Rojo",
    imagenBlog:"https://lh3.googleusercontent.com/HG3lAT6YVxt0eoXIQSyKvGCPtXSeOwxpxOo82859YLlF2ZpztNXcivdR_V9WsyBb3XVPoFlfFYxvgFK4NzUE31SqZmYT9d5ztuum4T50twe3MYZp_Bocv_5fW7SNZF0grg688ErxJw=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Saber del rojo camina victoriosa cargando su espada sobre el hombro mientras las ruinas dejadas por su ultimo ataque se desmoronan detrás de ella. Repentinamente se detiene al ver a su maestro sentado en el suelo mientras fuma un cigarrillo.",
    fecha:"Octubre 16, 2019",
    tipo:"Serie",
    titulo:"Fate Apocripha",
    capitulo:"Capitulo: 23",
    tiempo:"Min. 11.5 - 14.5",
    link:"series/la_ultima_batalla_del_saber_rojo.html"
  },
  {
    nombreBlog:"La Batalla Contra el Golem Invencible",
    imagenBlog:"https://lh3.googleusercontent.com/1W7Ga1w7QKraLzofTPE7-Gq6dXs5cDmDXfg7RcEdScwbfYt08V2vT7DvR6sIgiY73iFNnogiXBVwA0aKdZMm91K99OiXy2sBrI3hyI7jmYZWjFFrT6WljblTX1-76mJhzYViACMuUw=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Ruler!!! Necesitamos otro servant!!!, tiene que haber alguno cerca! -Grito con fuerza Archer del negro hacia en donde se encontraba Ruler-",
    fecha:"Septiembre 26, 2019",
    tipo:"Serie",
    titulo:"Fate Apocripha",
    capitulo:"Capitulo: 14",
    tiempo:"Min. 15 - 21",
    link:"series/la_batalla_contra_el_golem_invencible.html"
  },
  {
    nombreBlog:"Un Nuevo Contrato",
    imagenBlog:"https://lh3.googleusercontent.com/_FLfEiPTxjLOA5otvmkNQr815X2z2rZrAzko7SF3x-3li_POHA5UU6RV5yX_eVjq7nNruD0XiRyYfKAMWQH6UgGn0kcVZbTYWDsLLUJb1T7lZQt2mXP61fHeAz_JuScTBIcn64_gtQ=w2400",
    autorBlog:"Artur Writes",
    sinopsis:"Rider te encuentras bien? -Pregunta Sieg levantándose apresuradamente hacia donde Rider se encontraba-",
    fecha:"Septiembre 09, 2019",
    tipo:"Serie",
    titulo:"Fate Apocripha",
    capitulo:"Capitulo: 13",
    tiempo:"Min. 11 - 13",
    link:"series/un_nuevo_contrato.html"
  },
]
